apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-resources-auto-rollouter.clusterRoleName" . }}
  labels:
    {{- include "k8s-resources-auto-rollouter.labels" . | nindent 4 }}
rules:
  - apiGroups: ["", "apps"]
    resources: ["deployments", "daemonsets", "statefulsets"]
    verbs: ["get", "patch", "list"]