apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "krar.clusterRoleName" . }}
  labels:
    {{- include "krar.labels" . | nindent 4 }}
  {{- with .Values.clusterRoleAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: ["", "apps"]
    resources: ["deployments", "daemonsets", "statefulsets"]
    verbs: ["get", "patch", "list"]