apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "krar.serviceAccountName" . }}
  labels:
    {{- include "krar.labels" . | nindent 4 }}
  {{- with .Values.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}